name: CI Pipeline

on:
  pull_request:
    branches:
     - devel
     - stage
     - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout respository
        uses: actions/checkout@v3

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15.5.1
      
      - name: install dependencies
        run: npm install

      - name: run linter
        run: npm run lint
      
      - name: run prettier (auto-fix)
        run: npm prettier --write .
      
      - name: run test
        run: CI=true npm run test

      - name: build the project
        run: npm run build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: deploy to s3 based on the target branch
        run: |
          if [ "${{ github.base_ref }}" == "devel" ]; then
            aws s3 sync ./public s3://fsl-devops-devel/ --delete
          elif [ "${{ github.base_ref }}" == "stage" ]; then
            aws s3 sync ./public s3://fsl-devops-stage/ --delete
          elif [ "${{ github.base_ref }}" == "prod" ]; then
            aws s3 sync ./public s3://fsl-devops-prod/ --delete
          else
            echo "Branch not configured for s3 deployment"
            exit 1
          fi